# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 04:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='한글성명을 입력해주세요.', max_length=30, verbose_name='성명(한글)')),
                ('name_en', models.CharField(help_text='영문성명을 입력해주세요.', max_length=30, verbose_name='성명(영문)')),
                ('email_address', models.EmailField(help_text='이메일주소를 입력해주세요.', max_length=254)),
                ('address', models.CharField(blank=True, help_text='사무실 주소를 입력해주세요.', max_length=100)),
                ('fax', models.CharField(blank=True, help_text='팩스 번호를 입력해주세요.', max_length=50)),
                ('unique_url', models.CharField(help_text='주소에 사용될 영문/숫자 혼합문자를 작성해주세요 (ex)영문성함, 사무소이름 등', max_length=50, unique=True)),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='lawyer/%Y/%m/%d')),
                ('fields', models.CharField(blank=True, help_text='관련업무분야를 선택해주세요.', max_length=50)),
                ('p_story', models.TextField(blank=True, help_text='경력/업무사례/저서/활동 등의 사항을 작성해주세요.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
