# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_auto_20180424_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='p_activity',
            field=models.TextField(blank=True, help_text='저서/활동을 작성해주세요.', verbose_name='저서/활동'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='p_certificate',
            field=models.CharField(default='2009/변호사(대한민국)', help_text='년도/자격을 작성해주세요. 예시)2004/변호사(대한민국)', max_length=50, verbose_name='자격취득'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyer',
            name='p_edu',
            field=models.TextField(blank=True, help_text='학력사항을 작성해주세요.', verbose_name='학력'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='p_prize',
            field=models.TextField(blank=True, help_text='수상내역을 작성해주세요.', verbose_name='수상'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='p_story',
            field=models.TextField(blank=True, help_text='경력 사항을 작성해주세요.', verbose_name='경력'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='unique_url',
            field=models.CharField(help_text='주소에 사용될 영문자(대소문자구분)를 작성해주세요 (ex)영문성함, 사무소이름 등', max_length=50, unique=True),
        ),
    ]
