# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0003_auto_20180425_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='intro',
            field=models.TextField(blank=True, help_text='"000변호사의 주된 업무분야는 xx,xx,xx 입니다. 0변호사는 ~한 활동을 하고 있고 ---."와 같은 형식으로 입력해주세요.', verbose_name='소개'),
        ),
    ]
